### ISSUE TITLE
Experience code edit doesn't works 

### ISSUE THREAD

**Issue by fliperaa** [wooslow/discord-farm-merge-valley-hack#12]
when i try edit value of experience in breakpoint

" return this[_0x2f4f33(0x25b2)]['experience']; "

just do the animation rewarding exp, but the value of my level xp does not change. 

how i resolve that ?

**Comment by soeviturek** [comment]
change the 'expReward' field in this function: return this[_0x59c98f(0x25b2)][_0x59c98f(0x4b90)];

**Comment by fliperaa** [comment]
@soeviturek worked, thanks <3
