### ISSUE TITLE
Developers find a way to stop debuggers

### ISSUE THREAD

**Issue by MahmoudBahar** [wooslow/discord-farm-merge-valley-hack#20]
every time i open the source file the code hits a point where a function is called and inside it there is a break point statement "debugger".

**Comment by PeterChiang0101** [comment]
enter this line to your console, and it will stop the looped debugger.
```
Function.prototype.constructor = function(){}
```
credit: https://www.cnblogs.com/niuwu/p/15136010.html

**Comment by LennyMcLennington** [comment]
> enter this line to your console, and it will stop the looped debugger.
> 
> ```
> Function.prototype.constructor = function(){}
> ```
> 
> credit: https://www.cnblogs.com/niuwu/p/15136010.html

Did not work for me, but I wrote this and it did work:

```js
old_function_constructor = Function.prototype.constructor

Function.prototype.constructor = new Proxy(old_function_constructor, {
    apply(target, thisArg, argumentsList) {
        if (argumentsList.length === 1 && argumentsList[0] === "debugger") {
            return () => {}
        }

        return Reflect.apply(target, thisArg, argumentsList)
    }
})
```

**Comment by wooslow** [comment]
updated

**Comment by LennyMcLennington** [comment]
@wooslow the method shown in the original causes the game to not function properly if you do it before the game is fully loaded, doing it via a Proxy to only target the anti debugger functions makes more sense, and doesn't break the game if done during loading.
