### ISSUE TITLE
New names

### ISSUE THREAD

**Issue by lifeindarkside** [wooslow/discord-farm-merge-valley-hack#21]
```return this['_data']['reward']``` = ```return this['_data']['rewar' + 'd']```
```return this[_0x315223(0x340f)]['expReward']``` = ```return this[_0x129fc0(0x21c2)][_0x129fc0(0x3dca) + _0x129fc0(0x40ff)]```

find with https://obf-io.deobfuscate.io/

**Comment by fAntMP** [comment]
Instead of 
`return this['_data']['rewar' + 'd']` 

I had to set breakpoint on this to get it to break for a reward:
`return this['_data'][_0x54880a(0x89c) + 'dData'];`

**Comment by Halfeez92** [comment]
> Instead of `return this['_data']['rewar' + 'd']`
> 
> I had to set breakpoint on this to get it to break for a reward: `return this['_data'][_0x54880a(0x89c) + 'dData'];`

Hi, could you explain more on this? Tried to find value but no avail.

**Comment by fAntMP** [comment]
> > Instead of `return this['_data']['rewar' + 'd']`
> > I had to set breakpoint on this to get it to break for a reward: `return this['_data'][_0x54880a(0x89c) + 'dData'];`
> 
> Hi, could you explain more on this? Tried to find value but no avail.

I don't know, I can find it without a problem with ctrl+f

**Comment by lifeindarkside** [comment]
For me perfectly work ```return this['_data']['rewar' + 'd']``` and ```return this[_0x315223(0x340f)]['expReward']```

**Comment by fAntMP** [comment]
> For me perfectly work `return this['_data']['rewar' + 'd']` and `return this[_0x315223(0x340f)]['expReward']`

In fact, I just tried it again and yes, `return this['_data']['rewar' + 'd']` works for me now. 
I don't know why yesterday it didn't trigger the breakpoint for me. 
And now, the `return this['_data'][_0x54880a(0x89c) + 'dData']` breakpoint doesn't get triggered any more. 
I have no idea what happened yesterday.

**Comment by wooslow** [comment]
updated
