### ISSUE TITLE
debugger paused

### ISSUE THREAD

**Issue by exor312** [wooslow/discord-farm-merge-valley-hack#24]
whenever i open the devtools it just keep on getting paused, even though the pause on uncaught exception and pause on caught exception is unchecked

please help

**Comment by exor312** [comment]
its doing something like this
![image](https://github.com/user-attachments/assets/18652cc0-fdd5-4aa8-8282-9d3a724a5a7e)

**Comment by Powerdude574** [comment]
Follow https://github.com/wooslow/discord-farm-merge-valley-hack/issues/20

**Comment by exor312** [comment]
thanks it works
