### ISSUE TITLE
Remove Resources

### ISSUE THREAD

**Issue by Xaszanyn** [wooslow/discord-farm-merge-valley-hack#27]
is there a way to bypass chopping trees or breaking stones?

**Comment by LennyMcLennington** [comment]
You can give every gameobject on the map the "shovelable" behaviour to be able to manually pick and choose which ones to remove, or I guess you could directly remove the gameobjects otherwise.

**Comment by bimaindrawans** [comment]
can you give me an example how to implement that ?

**Comment by LennyMcLennington** [comment]
> can you give me an example how to implement that ?

@bimaindrawans Based on [this comment](https://github.com/wooslow/discord-farm-merge-valley-hack/issues/22#issuecomment-2325599941):

I HAVE NOT TESTED THIS CODE SO I DO NOT KNOW IF IT WORKS (but it should **delete all currently revealed obstacles in the map**):
`worldServices.world.getAllGameObjects().filter(x=>x.hasBehavior("hitpoints") && !x.hasBehavior("shovelable") && !x.hasBehavior("movable")).forEach(x=>worldServices.world.removeGameObject(x))`

I HAVE TESTED THIS CODE AND IT DOES WORK, it will **make all the obstacles shovelable and movable**:
`worldServices.world.getAllGameObjects().filter(x=>x.hasBehavior("hitpoints") && !x.hasBehavior("shovelable") && !x.hasBehavior("movable")).forEach(x=>x.addBehavior(new behaviors.shovelable).addBehavior(new behaviors.movable))`

**Comment by bimaindrawans** [comment]
> worldServices.world.getAllGameObjects().filter(x=>x.hasBehavior("hitpoints") && !x.hasBehavior("shovelable") && !x.hasBehavior("movable")).forEach(x=>{x.addBehavior(new behaviors.shovelable); x.addBehavior(new behaviors.movable)})

![image](https://github.com/user-attachments/assets/94279389-55dc-4b24-8ee7-80598e3bedf4)

worked perfectly, thankyouuu
