### ISSUE TITLE
main.js has been patched - solution no longer works

### ISSUE THREAD

**Issue by mop1987** [wooslow/discord-farm-merge-valley-hack#4]
You're telling people to check the readme file but this solution from readme no longer works 

cannot perform "step 2" as "this._data.reward" does not exist therefore cannot add breakpoint.

![image](https://github.com/user-attachments/assets/b4f105ca-59f7-4cb3-bb0a-b28b4d30c5b3)

**Comment by wooslow** [comment]
<img width="967" alt="image" src="https://github.com/user-attachments/assets/09ea87d9-58f8-400d-b30a-91f85e151300">

**Comment by mop1987** [comment]
no one has any idea what that table above means......the instructions are unclear, remove anything which is no longer relevant from your readme file

**Comment by wooslow** [comment]
If you can't understand, that's not my problem.
