### ISSUE TITLE
"return this[_0x86f480(0x25b2)]['reward'];" breakpoint has no local under scope

### ISSUE THREAD

**Issue by kyourandesu** [wooslow/discord-farm-merge-valley-hack#5]
The image you uploaded shows you changing the data under local but after adding a breakpoint to "return this[_0x86f480(0x25b2)]['reward'];", there isn't any data to change. 

![image](https://github.com/user-attachments/assets/8b21902c-c31d-4aee-b096-edd0e46cca82)

**Comment by themirze** [comment]
did you find solution?

**Comment by kyourandesu** [comment]
> did you find solution?

no, author has not replied

**Comment by themirze** [comment]
Probably fixed

**Comment by kyourandesu** [comment]
> Probably fixed

did you figure out how to do so? if so can you tell me how you did it?

**Comment by wooslow** [comment]
watch the video on youtube
